
apiVersion: batch/v1
kind: CronJob
metadata:
  name: castai-node-drainer
  namespace: castai-agent
spec:
  schedule: "0 0 * * 0" 
  timeZone: Etc/UTC
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: castai-node-drainer
          restartPolicy: Never
          terminationGracePeriodSeconds: 60
          tolerations:
          - key: "CriticalAddonsOnly"
            operator: "Equal"
            value: "true"
            effect: "NoSchedule"
          nodeSelector:
            kubernetes.azure.com/mode: system
          containers:
          - name: castai-node-drainer
            image: castai/castai-node-rotate:latest
            env:
            - name: DELAY_AFTER_READY
              value: "20"
            - name: CRITICAL_WORKLOADS
              value: "app.kubernetes.io/name=castai-agent,app.kubernetes.io/name=castai-cluster-controller,app.kubernetes.io/name=another-critical-pod"
            - name: MIN_READY_NODES
              value: "2"
            - name: TOTAL_WAIT_CYCLES
              value: "25"
            - name: STARTUP_SLEEP_TIME
              value: "30"
            - name: DELAY_WAIT_PENDING_PODS
              value: "30"
            - name: MIN_NODE_AGE_DAYS
              value: "7"
            - name: NODE_DRAIN_TIMEOUT 
              value: "1200"
            resources:
              limits:
                memory: 500Mi
              requests:
                cpu: 50m
                memory: 500Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: castai-node-drainer
  namespace: castai-agent
---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: castai-node-drainer
# rules:
# - apiGroups:
#   - ""
#   resources:
#   - events
#   verbs:
#   - create
# - apiGroups:
#   - ""
#   resources:
#   - pods
#   - namespaces
#   verbs:
#   - list
#   - delete  # Added the 'delete' verb for pods
# - apiGroups:
#   - "apps"
#   resources:
#   - pods/eviction
#   verbs:
#   - create
# - apiGroups:
#   - ""
#   resources:
#   - nodes
#   verbs:
#   - get
#   - watch
#   - list
#   - patch
# ---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: castai-node-drainer
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: castai-node-drainer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: castai-node-drainer
subjects:
- kind: ServiceAccount
  name: castai-node-drainer
  namespace: castai-agent